### PR TITLE
Compatibility improvements

### LINKED ISSUE #151: NoSuchMethodError when application is compiled with Kotlin 1.5.0-RC
```kotlin
Exception in thread "main" java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.getSeconds(int)'
	at io.rsocket.kotlin.keepalive.KeepAlive.<init>(KeepAlive.kt:22)
	at io.rsocket.kotlin.core.RSocketConnectorBuilder$ConnectionConfigBuilder.<init>(RSocketConnectorBuilder.kt:70)
	at io.rsocket.kotlin.core.RSocketConnectorBuilder.<init>(RSocketConnectorBuilder.kt:28)
	at io.rsocket.kotlin.core.RSocketConnectorBuilderKt.RSocketConnector(RSocketConnectorBuilder.kt:112)
	at io.rsocket.kotlin.core.RSocketConnectorBuilderKt.RSocketConnector$default(RSocketConnectorBuilder.kt:111)
	at io.rsocket.kotlin.transport.ktor.client.RSocketSupport$Config.<init>(RSocketSupport.kt:30)
	at io.rsocket.kotlin.transport.ktor.client.RSocketSupport$Feature.prepare(RSocketSupport.kt:36)
	at io.rsocket.kotlin.transport.ktor.client.RSocketSupport$Feature.prepare(RSocketSupport.kt:33)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:72)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:18)
	at io.ktor.client.HttpClientConfig.install(HttpClientConfig.kt:92)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:168)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:81)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:43)
```

I have the following rsocket-kotlin versions:

```gradle
    implementation("io.rsocket.kotlin:rsocket-core:0.12.0")
    implementation("io.rsocket.kotlin:rsocket-transport-ktor:0.12.0")
    implementation("io.rsocket.kotlin:rsocket-transport-ktor-client:0.12.0")
    implementation("io.rsocket.kotlin:rsocket-transport-ktor-server:0.12.0")
```

### PR DESCRIPTION
**Pull request by whyoleg**
* remove FlowPreview, InternalCoroutinesApi, ExperimentalCoroutinesApi, ExperimentalStdlibApi, ExperimentalUnsignedTypes, ExperimentalTime, KtorExperimentalAPI opt-in usage
* use ordinary class instead of inline for Version
* rewrite KeepAlive to use experimental time only in one place with appropriate annotation, don't use data class
* minor rewrite of PayloadMimeType - change default mime type to "application/octet-stream", don't use data class

fixes #151

### CODE REVIEW

File: rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt [hunk 1]
```diff
@@ -64,7 +65,9 @@ internal class SetupFrame(
 
     override fun StringBuilder.appendSelf() {
         append("\nVersion: ").append(version.toString()).append(" Honor lease: ").append(honorLease).append("\n")
-        append("Keep alive: interval=").append(keepAlive.interval).append(", max lifetime=").append(keepAlive.maxLifetime).append("\n")
+        append("Keep alive: interval=").append(keepAlive.intervalMillis)
+            .append(" ms, max lifetime=").append(keepAlive.maxLifetimeMillis)
```
Comment (yschimke) [inline rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt:69]: suggest splitting this like the other lines. "max lifetime" starting on it's own line, this is debug code effectively so not performance critical.

File: rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAlive.kt [hunk 2]
```diff
@@ -16,9 +16,25 @@
...
+)
+
+public class KeepAlive(
+    public val intervalMillis: Int = 20 * 60 * 1000, // 20 seconds
+    public val maxLifetimeMillis: Int = 90 * 60 * 1000 // 90 seconds
+)
+
+@SharedImmutable
+internal val DefaultKeepAlive = KeepAlive(
+    intervalMillis = 20 * 60 * 1000, // 20 seconds
```
Comment (yschimke) [inline rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAlive.kt:38]: minutes?

File: rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAliveHandler.kt [hunk 3]
```diff
@@ -21,36 +21,34 @@ import io.rsocket.kotlin.*
...
-import kotlin.time.TimeSource.*
 
-@OptIn(ExperimentalTime::class)
 internal class KeepAliveHandler(
     private val keepAlive: KeepAlive,
     private val offerFrame: (frame: Frame) -> Unit,
 ) {
 
-    private val lastMark = atomic<TimeMark?>(null)
+    private val lastMark = atomic(currentMillis())
```
Comment (yschimke) [inline rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAliveHandler.kt:30]: Can we use Kotlin TimeSource here?

File: rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAlive.kt (hunk 2 above)
Comment (whyoleg) [reply rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAlive.kt:38]: oops :)

File: rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAliveHandler.kt (hunk 3 above)
Comment (whyoleg) [reply rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAliveHandler.kt:30]: it was, before, but it's still experimental API, in kotlin 1.5 f.e. duration APIs changed in non backward compatible way.
After it will become stable, yes we can.

**Review by yschimke — APPROVED** [review]
